import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/widgets/plans_create_task_activity_record_widget/plans_create_task_activity_record_widget_cubit.dart';

class PlansCreateTaskActivityRecordWidgetController extends BaseController<PlansCreateTaskActivityRecordWidgetCubit>{}