import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/widgets/plans_payment_options_modal_widget/plans_payment_options_modal_widget_cubit.dart';

class PlansPaymentOptionsModalWidgetController extends BaseController<PlansPaymentOptionsModalWidgetCubit>{

}