import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/widgets/plans_plan_subscription_details_expired_widget/plans_plan_subscription_details_expired_widget_cubit.dart';

class PlansPlanSubscriptionDetailsExpiredWidgetController extends BaseController<PlansPlanSubscriptionDetailsExpiredWidgetCubit>{}
