import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/screens/plans_routine_intermediate_screen/plans_routine_intermediate_screen_cubit.dart';

class PlansRoutineIntermediateScreenController extends BaseController<PlansRoutineIntermediateScreenCubit>{}

