import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/widgets/plans_plan_details_row_swiper_widget/plans_plan_details_row_swiper_widget_cubit.dart';

class PlansPlanDetailsRowSwiperWidgetController extends BaseController<PlansPlanDetailsRowSwiperWidgetCubit>{

}