import 'package:beebloom_water_tracker/app/core/controllers/base_controller.dart';
import 'package:beebloom_water_tracker/app/plans/screens/plans_plan_home_past_future_screen/plans_plan_home_past_future_screen_cubit.dart';

class PlansPlanHomePastFutureScreenController extends BaseController<PlansPlanHomePastFutureScreenCubit>{}

